### ISSUE TITLE
Make homepage redesign

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wporg-make#2]
The current Make homepage needs to be updated to match the rest of the WordPress.org redesign.

### Current design:

<img src="https://github.com/user-attachments/assets/15e8b759-830c-4a5e-a0a2-0addc2ad4593" width="600">

### Proposed design (TBC):

<img src="https://github.com/user-attachments/assets/14fec9ea-c856-49f6-8e1c-11e9873baa58" width="600">

**Comment by adamwoodnz** [comment]
@WordPress/meta-design can we move ahead with the homepage design?

**Comment by jasmussen** [comment]
Yes, though please keep the existing team icons! You can put them in a circle or not, put them left of the title or not. 

Please be mindful of the correct accessibility of the particular collapsibles; if this ends up becoming a headache, it's okay to launch without the collapsibles, i.e. look much closer to the existing layout that's shipping at the moment.

**Comment by adamwoodnz** [comment]
> it's okay to launch without the collapsibles, i.e. look much closer to the existing layout that's shipping at the moment.

I've shipped an initial implementation closer to the existing layout, and opened a separate [sub issue for the interactivity](https://github.com/WordPress/wporg-make/issues/15).

**Comment by fcoveram** [comment]
I see some misalignments that seemed caused by the font and its x baseline. Here are some examples.

| Section | Header |
|:---|:---|
| Design | ![Design header on Make page](https://github.com/user-attachments/assets/0369deb9-f5ca-46b3-afc0-b8a5cf333594) |
| Meta | ![Meta header on Make page](https://github.com/user-attachments/assets/368bcca8-4b7a-4692-9835-f4061817f9ac)
| Sustainability | ![Sustainability header on Make page](https://github.com/user-attachments/assets/1853bc80-87b5-4d36-acfb-108d71100b3a) |

We could try removing the circular wrapper while keeping the icon on the same position. What do you think @jasmussen?

**Comment by jasmussen** [comment]
Huh, that's a curious one indeed. It looks like there's nothing wrong with the CSS, but the globe in question is off-center in the Dashicons font itself.

Honestly it feels like an argument to update these icons to SVGs, and we can offer a consistent upgrade here to teams interested. But this is likely best done as a separate sprint. Whether we keep the circle now or not, I've not strong opinion on!

**Comment by fcoveram** [comment]
I agree with updating the icons. Suggest even new ones. Meanwhile, I would remove the circle to keep the layout proposed balanced.

**Comment by adamwoodnz** [comment]
> Honestly it feels like an argument to update these icons to SVGs, and we can offer a consistent upgrade here to teams interested.

Noting that 2 teams already have SVG icons (Openverse and Core Performance), so the code is there to replace all of them.

**Comment by fcoveram** [comment]
That sounds great. Thanks @adamwoodnz

**Comment by fcoveram** [comment]
Based on [this ping](https://github.com/WordPress/wporg-make/issues/31#issuecomment-2451520064), I took a look at the homepage and worked on an idea that involves the following tickets:
* #31 
* #15 
* #16 

## Homepage (i2.4)

Most work was revisiting the hero section and how teams are displayed in the main content area. Here is a mockup.

![Mockup of Make WordPress' homepage](https://github.com/user-attachments/assets/f27302ff-b68d-42e3-b582-74e19f6c7618)

The teams area goes back to make all content visible and the page larger. I don't see this as a problem as the new table arrangement makes it easier to identify the team name.

The icons are from the previous mockup in #15, but the final ones depend on the answer to [this question](https://github.com/WordPress/wporg-make/issues/16#issuecomment-2451510414).

I'm aware that some teams don't have the meeting info, and therefore, the last column will be empty. Still, I see benefits in identifying which teams have upcoming and periodic meetings.

What do you think of this?

**Comment by ndiego** [comment]
This mockup looks lovely @fcoveram! The column approach feels easier to read, and the expressive header really embodies the "community" of Make. I recommend we move forward with this approach.

**Comment by adamwoodnz** [comment]
Looks great to me too! Any feedback @jasmussen? Otherwise I'll get started 🙂

**Comment by jasmussen** [comment]
Looks great to me.

[I'd include your note here, that we can update the copy](https://github.com/WordPress/wporg-make/issues/31#issuecomment-2474991362).

**Comment by fcoveram** [comment]
I fixed the duplicated paragraph mentioned in #31 and updated the ["Design"](https://www.figma.com/design/pHuv2kwNi4Uf17K9GLXmgA/Make-WordPress-%26-Make-P2s?node-id=1006-1013&node-type=section&m=dev) page to reflect the final designs.
