### ISSUE TITLE
Heading on component pages look off.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-make#28]
Looking at https://make.wordpress.org/meta/pledges/, it appears like the headings `font-weight` are too light.

## Screenshot

![Image](https://github.com/user-attachments/assets/aad8352d-634b-4518-9b8b-08c6fd1325e4)

**Comment by adamwoodnz** [comment]
eg. https://make.wordpress.org/meta/components/news-wordpress-org-news/
