### ISSUE TITLE
Suggested edits for the new Make homepage

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-make#31]
I bundled a few issues together in this issue since all impact the Make homepage. 

### Header

I think we need to do something a bit different with this section. Translating the old content into the new design does not work as well IMO. It feels very "empty".

| New theme | Old theme |
|-|-|
|![Image](https://github.com/user-attachments/assets/eb7a1eb1-f507-47f4-a236-108c1b41b98b)|![Image](https://github.com/user-attachments/assets/bb5b9c20-d9b7-47a3-9035-6bffc1a67740)|

### Footer 

I don't think we need this content since the local navigation exists with these same links. 

![Image](https://github.com/user-attachments/assets/44413379-46ef-409a-a39e-a4e248d70a2d)

**Comment by adamwoodnz** [comment]
@WordPress/meta-design your input on this one would be appreciated please.

**Comment by jasmussen** [comment]
I'd be drawn to reuse the design pattern from FFTF: https://wordpress.org/five-for-the-future/

That would afford an image, at least, possibly an illustration below, if need be. Not the same image or illustration, but the design pattern. @fcoveram has a full plate, but he might have better instincts in that same vein.

**Comment by adamwoodnz** [comment]
Who can write some fresh copy for this? The [new design](https://www.figma.com/design/pHuv2kwNi4Uf17K9GLXmgA/Make-WordPress-%26-Make-P2s?node-id=1313-19980&m=dev) looks great, but still uses the existing copy.

![Image](https://github.com/user-attachments/assets/847e40f5-4d32-4d33-b46a-d2eee273ff47)

**Comment by fcoveram** [comment]
Oh forgot to delete the paragraph below the "Teams" heading. It's now correct and all final mockups are in the "[Design](https://www.figma.com/design/pHuv2kwNi4Uf17K9GLXmgA/Make-WordPress-%26-Make-P2s?node-id=1006-1013&node-type=section&m=dev)" page.

**Comment by michaelpick** [comment]
Hey @jasmussen. As we chatted about, Francisco and I had a look at this and left a few ideas for potential copy iteration as comments in the [design mockup](https://www.figma.com/design/pHuv2kwNi4Uf17K9GLXmgA?node-id=1395-20667#1028094339). Let me know if we can help with anything else.

**Comment by fcoveram** [comment]
Thanks for all the suggestions @michaelpick and @alvezfrancese. Glad to see another Francisco contributing 😄 

I agree with the suggestions, but I'm not sure about the team descriptions. If the teams build those, we should involve them in copy revision.

Thoughts?

**Comment by michaelpick** [comment]
Hi @fcoveram. By all means! Our suggestions are mostly to try and get things a slightly more consistent place, but please do feel free to involve the teams or put this on pause if that isn't viable at the moment.

**Comment by fcoveram** [comment]
Thanks @michaelpick

**Comment by ndiego** [comment]
@adamwoodnz I added an updated suggestion for the opening copy [here](https://www.figma.com/design/pHuv2kwNi4Uf17K9GLXmgA?node-id=1395-20667#1028095398).

**Comment by adamwoodnz** [comment]
I used the suggestions for the header copy but have left the team descriptions for now. Thanks all for your input!

**Comment by fcoveram** [comment]
I updated the homepage mockup with the copy suggested for the hero section

**Comment by ndiego** [comment]
Looks great!
