### ISSUE TITLE
Add local nav to Team Updates and Project Updates if possible

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-make#34]
I am not sure this is possible, but it feels like the local nav should be present on the Team Updates and Project Updates pages like it is for the Meeting page. I get why they don't, though.

| Meeting | Project Updates | Team Updates |
|-|-|-|
|![Image](https://github.com/user-attachments/assets/997870ba-a7d7-4819-9d03-5e02110c8555)|![Image](https://github.com/user-attachments/assets/d83d3daf-bc48-41bb-bd6d-961b81984e5e)|![Image](https://github.com/user-attachments/assets/a34200d9-a834-4346-9237-28b0cb465e8d)|

What do you think @adamwoodnz @fcoveram

**Comment by adamwoodnz** [comment]
Yeah I tend to agree. This should be a no-code change, as the local nav for each blog is derived from the primary menu for that site. I'll wait for @fcoveram to respond first.

**Comment by fcoveram** [comment]
Local nav should always be present, as per [this documentation](https://www.figma.com/design/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library?node-id=561-1216&node-type=canvas&m=dev) in the Design Library.

**Comment by adamwoodnz** [comment]
> Local nav should always be present, as per [this documentation](https://www.figma.com/design/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library?node-id=561-1216&node-type=canvas&m=dev) in the Design Library.

Ok, I'll add it.

A bit of context: what's not obvious is that these are actually separate Make blog sites (like Design, Core, Meta, etc), so having the local nav on those blogs use the home local nav is unusual, when considering them as standalone sites. Given they are not linked to from anywhere else I don't think there are any issues with this.

**Comment by adamwoodnz** [comment]
I've added the local nav to those 2 blogs. There is one inconsistency left in that the site title shows the name of that blog, eg. Project Updates looks like this:

![Image](https://github.com/user-attachments/assets/648c526c-4fc0-4e54-b95c-802d4f0b12c6)

Changing the title of each of these blogs to 'Make WordPress' would fix this, but I'm not sure whether that would cause confusion in other ways.

**Comment by fcoveram** [comment]
Thanks for the context @adamwoodnz. I see your point and understand the reason, but given that Project Updates and Team Updates have the layout and structure of make blogs, the navigation is consistent with most sections. Meeting looks more like an internal page, similar to [the page](https://events.wordpress.org/upcoming-events/) listing all WordPress events, but I assume that "converting" that site into an "internal page" is out of the update scope.

 > Changing the title of each of these blogs to 'Make WordPress' would fix this, but I'm not sure whether that would cause confusion in other ways.

To reduce confusion chances, we could keep the site link in local nav in active state (text in bold). So when visiting the Project Updates site, the "Project Updates" link in local nav is in bold all the time. This is visually consistent with most local nav updates.

So when scrolling down, it should look like this

![Image](https://github.com/user-attachments/assets/0db2b566-86af-4749-8101-cbd76c2a676f)

What do you think of this?

**Comment by adamwoodnz** [comment]
> Meeting looks more like an internal page, similar to [the page](https://events.wordpress.org/upcoming-events/) listing all WordPress events, but I assume that "converting" that site into an "internal page" is out of the update scope.

Meetings is actually an internal page, and I'm not sure why it's not showing an active state. I'll investigate and aim to have all the items in this local nav showing as active accordingly 👍 

Rather than renaming the Team Updates and Project Updates blogs, I think I'll use a filter to change the site-title block in the local nav bar to display 'Make WordPress', so they also match the home site.
