### ISSUE TITLE
Update OpenGraph image

### ISSUE THREAD

**Issue by fcoveram** [WordPress/wporg-make#41]
We could update the current OpenGraph image to make it consistent with latest updates. The current looks like this

![Image](https://github.com/user-attachments/assets/eb28eb33-2e9d-4fa3-b7fc-5ef0c6482f92)

There is already a version added in the [Scratchpad file](https://www.figma.com/design/wgwqNZTmYbvtC5LMG1XTVC/Open-Graph%E2%80%A8images---Scratchpad-file?node-id=1001-403), but wondering if the tagline sentence looks good or not.

![Heading showing "Make WordPress" over a dark background with a dot pattern](https://github.com/user-attachments/assets/2cc16382-eb15-43c7-a450-89a0c7cc8a9c)

**Comment by fcoveram** [comment]
I revisited the tagline and here is a new version of the image

![Image](https://github.com/user-attachments/assets/d070713f-cc7b-459f-8bc0-2d496c7dcc2a)

**Comment by adamwoodnz** [comment]
![Image](https://github.com/user-attachments/assets/d5e4b94b-8623-4c1b-a6c0-2698c8b4e5d0)
